[colors]
dark_red   = "#8b0000"
crimson    = "#cc1100"
red        = "#ff0000"
orange_red = "#ff3300"
orange     = "#ff6600"
amber      = "#ff9900"
yellow     = "#ffcc00"
white_hot  = "#ffffcc"

[visualizer]
gradient    = ["dark_red", "crimson", "red", "orange_red", "orange", "amber", "yellow", "white_hot"]
wave_color  = "orange"
scope_color = "yellow"
