[colors]
deep_purple = "#2b0057"
hot_pink    = "#ff2975"
neon_pink   = "#ff6ac1"
cyan        = "#00e5ff"
neon_blue   = "#79e8ff"

[visualizer]
gradient    = ["deep_purple", "hot_pink", "neon_pink", "cyan", "neon_blue"]
wave_color  = "hot_pink"
scope_color = "cyan"
